### ISSUE TITLE
ImportError: cannot import name 'NeuralSDE_forecasting' from 'models_sde.neuralsde'

### ISSUE THREAD

**Issue by suannairen** [yongkyung-oh/Stable-Neural-SDEs#1]
When I use benchmark_forecasting ,I need import NeuralSDE_forecasting from models_sde.neuralsde,but models_sde.neuralsde don`t have NeuralSDE_forecasting moudle
![image](https://github.com/yongkyung-oh/Stable-Neural-SDEs/assets/89651140/ed59c97e-9a86-4ce6-8e64-76db1dfddc60)
![image](https://github.com/yongkyung-oh/Stable-Neural-SDEs/assets/89651140/9b2506a6-8c94-4b18-9500-51be7ad34e13)

**Comment by yongkyung-oh** [comment]
Thank you for your comment. I found that the class is missed in the original file. 
Please check the updated one.

**Comment by SDH-IT-HO** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
fpgaq, @mjtpena, @ayoubbenmahiddine, @alvaroserrrano, @Paebi5, @Martinprobu, @Gonzapepe, @cwcheak, @Jakkc, @iHusk, @vicentkasumba23, @EmanHerawy, @pvela, @alifiratdemirbas, @yannhowe, @dimitritholen, @freddymu, @snfnwgi, @vvdhout, @roudra323, @PaolaCartala, @sot528, @jefflam, @RealDikang, @roiyz, @nbeerbower, @samueldanso, @elqla, @kkomelin, @bobbar17, @ssteiger, @mtorry225, @mehmeta, @salis, @0xFanz, @Ctulu82, @akalautaro, @iftzp, @suolike, @blackhunterfox, @girish979, @javimaravillas, @leopaul29, @trenchmortar, @myaltunay, @dmanning23, @physician, @Hsien-HsiuLiao, @hqwangningbo, @Florence1279
