### ISSUE TITLE
Code problem

### ISSUE THREAD

**Issue by BANLANGEN11** [yongkyung-oh/Stable-Neural-SDEs#2]
Which code is the code of the paper "STABLE NEURAL STOCHASTIC DIFFERENTIAL EQUATIONS IN ANALYZING IRREGULAR TIME SERIES DATA"

**Comment by yongkyung-oh** [comment]
Hi, Thank you for your interest. This repository is the collection of the codes for the paper: Stable Neural Stochastic Differential Equations in Analyzing Irregular Time Series Data.

In other words, we used all codes for the paper, but each direcotry includes different pipeline for the experiments (such as interpolation, forecasting, and classification). Which task are you interested? I can explain the details to reproduce the experiments in the paper.

**Comment by BANLANGEN11** [comment]
Thank you very much. I still have a few questions. Which files are the code for model Neural LSDE,Neural LNSDE and Neural GSDE?

**Comment by yongkyung-oh** [comment]
Because there are multiple combinations of drift and diffusion terms, we assign the model name as 'neuralsde_{input_option}_{noise_option}' as described in [README.md](https://github.com/yongkyung-oh/Stable-Neural-SDEs/blob/main/README.md). 

I'll update the basic tutorial code this week. What task are you currently working on?

**Comment by BANLANGEN11** [comment]
Ok, thank you very much. I've been working on an irregular time series forecasting task. Just finished learning NODE, NCDE and NSDE.

**Comment by yongkyung-oh** [comment]
I have updated a tutorial focusing on the reconstruction task. I believe it will be beneficial for your work: [tutorial](https://github.com/yongkyung-oh/Stable-Neural-SDEs/tree/main/tutorial).

Furthermore, the experimental code includes some additional techniques (or tricks) that you might find useful. Please let me know if you need further help.

**Comment by BANLANGEN11** [comment]
Thank you very much for your contribution, I am very moved. Now I have no problem, I will learn your code next. Thank you for your patient guidance.
